spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/like1?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&noAccessToProcedureBodies=true&zeroDateTimeBehavior=convertToNull&useSSL=true
    password: password
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

    ############################
    ##thymeleaf页面模板配置


    thymeleaf:
      prefix: classpath:/
      suffix: .html
      cache: false #关闭缓存
################################

#配置mybatis.
#
######################################
mybatis:
  type-aliases-package: com.project.pojo         # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml     # mapper映射文件
  configuration:                               #打印执行sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#
#mybatis mapper设置.
#通用mapper配置
######################################
mapper:
  mappers: com.project.my.mapper.MyMapper
  not-empty: false            #在进行数据库操作的时候，判断表达式 username！=null，是否追加user
  identity : MYSQL

#配置Tomcat.
#web访问端口号 8088
######################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 80KB
######################################